name: PHP Composer

on:
  push:
    branches: [ master, framework ]
  pull_request:
    branches: [ master, framework ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    # - name: Setup PHP with composer v2
    #   uses: shivammathur/setup-php@2.6.0
    #   with:
    #     php-version: '7.4'
    #     tools: composer

    - name: Validate composer.json
      run: composer validate --no-check-lock

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run CI
      run: composer ci
